#!/usr/bin/env bash
# Transfers a file to a server from client using scp

# Display usage if less than 4 args
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
HOST="$2"
USERNAME="$3"
SSH_KEY="$4"

# Exit if file or key does not exist
[ ! -f "$FILE_PATH" ] && exit 1
[ ! -f "$SSH_KEY" ] && exit 1

# Correct permissions for SSH key
chmod 600 "$SSH_KEY"

# Transfer file to user's home directory
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$HOST:~/"
