#!/usr/bin/env bash
# Configure nginx to redirect /redirect_me with 301

# Install nginx
apt-get update -y
apt-get install -y nginx

# Set up default site
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html;

    # 301 redirect for /redirect_me
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart nginx
service nginx restart
