#!/usr/bin/env bash
# Install nginx, setup root index, redirect, and custom 404 page

apt-get update -y
apt-get install -y nginx

# Root page (task 1)
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Custom 404 page (task 4)
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Nginx config
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html;

    # Redirect (task 3)
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Custom 404 page
    error_page 404 /404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart nginx
service nginx restart
